name: AdGuard Home DNS Rewrite
description: Action to maintain a list of DNS rewrites in AdGuard instances in sync using GitOps.
inputs:
  DNS_FILE:
    description: "Path to the file (json) containing the DNS rewrites."
    required: true
  ADGUARD_USERNAME:
    description: "Username for your AdGuard instance."
    required: true
  ADGUARD_PASSWORD:
    description: "Password for your AdGuard instance."
    required: true
  ADGUARD_URL:
    description: "URL for your AdGuard instance (http(s)//my.instance:443). Must be accessible from your GitHub Actions runner."
    required: true
runs:
  using: "composite"
  steps:
    - name: Mask secrets
      run: |
        echo "::add-mask::${{ inputs.ADGUARD_USERNAME }}"
        echo "::add-mask::${{ inputs.ADGUARD_PASSWORD }}"
      shell: bash
    - name: Check if Python 3.x is installed
      id: check-python
      run: |
        if python3 --version | grep "Python 3."; then
          echo "python_installed=true" >> $GITHUB_ENV
        else
          echo "python_installed=false" >> $GITHUB_ENV
        fi
    - name: Install python
      if: env.python_installed == 'false'
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: python3 -m pip install -r "${{ github.action_path }}/requirements.txt"
      shell: bash
    - name: Update DNS Rewrites
      env:
        ADGUARD_INSTANCE: ${{ inputs.ADGUARD_URL }}
        ADGUARD_USERNAME: ${{ inputs.ADGUARD_USERNAME }}
        ADGUARD_PASSWORD: ${{ inputs.ADGUARD_PASSWORD }}
        DNS_JSON_FILE: ${{ inputs.DNS_FILE }}
      run: |
        python3 "${{ github.action_path }}/update_dns.py"
      shell: bash
